question_data = [
    {"category": "History", "type": "boolean", "difficulty": "easy",
                                      "question": "The Cold War ended with Joseph Stalin's death.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "The movie The Nightmare before Christmas was all done with physical objects.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "Video streaming website YouTube was purchased in it's entirety by Facebook for US$1.65 billion in stock.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "The music video to The Buggle's Video Killed the Radio Star was the first music video to broadcast on MTV.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "Gumbo is a stew that originated in Louisiana.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Art", "type": "boolean", "difficulty": "easy",
                                      "question": "Leonardo da Vinci's Mona Lisa does not have eyebrows.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Super Mario , collecting 100 coins on a level will give you a 1-UP.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Mario Kart 64, Waluigi is a playable character.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "The 2010 film The Social Network is a biographical drama film about MySpace founder Tom Anderson.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                                      "question": "The Berenstein Bears is the correct spelling of the educational children's book series' name.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "There is a city called Rome in every continent on Earth.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "Alaska is the largest state in the United States.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Sports", "type": "boolean", "difficulty": "easy",
                                      "question": "Peyton Manning retired after winning Super Bowl XLIX.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Half-Life 2 runs on the Source Engine.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In the original script of The Matrix, the machines used humans as additional computing power instead of batteries.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
                                      "question": "The communication protocol NFC stands for Near-Field Control.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "Ada Lovelace is often considered the first computer programmer.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                                      "question": "An atom contains a nucleus.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "Ottawa is the capital of Canada.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                      "difficulty": "easy", "question": "No Game No Life first aired in 2014.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The ultimate phrase used by Pharah from Overwatch is: Justice rains from above!",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In the Half-Life series, H.E.V stands for Hazardous Evasiveness Vest",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "HTML stands for Hypertext Markup Language.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Sonic the Hedgehog universe, Tails real name is Miles Prower.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "The song Stronger Than You is a single by Estelle, who played Garnet in Steven Universe.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Sports", "type": "boolean", "difficulty": "easy",
                                      "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The names of Tom Nook's cousins in the Animal Crossing franchise are named Timmy and Jimmy.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                                      "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In the movie The Revenant, DiCaprio's character hunts down the killer of his son.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Animals", "type": "boolean", "difficulty": "easy",
                                      "question": "Cats have whiskers under their legs.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "History", "type": "boolean", "difficulty": "easy",
                                      "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "Scatman John's real name was John Paul Larkin.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                                      "question": "Klingons express emotion in art through opera and poetry.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Art", "type": "boolean", "difficulty": "easy",
                                      "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                                      "difficulty": "easy",
                                      "question": "Waylon Smithers from The Simpsons was originally black when he first appeared in the series.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "Michael Jackson wrote The Simpsons song Do the Bartman.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "History", "type": "boolean", "difficulty": "easy",
                                      "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "There is an island in Japan called kunoshima, A.K.A. Rabbit Island, so named because of it's huge population of rabbits.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "John Williams composed the music for Star Wars.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                                      "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Codemasters is the developer of the Gran Turismo series.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "Jingle Bells was originally meant for Thanksgiving",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "Ping-Pong originated in England", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Space Station 13,  the station has a clown aboard it.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}
]
